apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-{{ .Chart.Name }}-{{ .Values.image.tag }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.selector.app }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .containerPort }}
    {{- end }}