replicaCount: 1

selector:
  app: l5-mc-apipost-v6

image:
  name: l2-multiapipost-v6
  tag: v6
  port: 80

service:
  ports:
    - name: http
      port: 8080
      containerPort: 80

ingress:
  path: /l5apipost6/Jokes
  port: 8080

