version: '3.4'

services:
  multiapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  multiapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  multiapipost:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

