version: '3.4'

services:
  multiapp:
    image: ${DOCKER_REGISTRY-}l2-multiapp-v6:v6
    build:
      context: .
      dockerfile: MultiApp/Dockerfile

  multiapipost:
    image: ${DOCKER_REGISTRY-}l2-multiapipost-v6:v6
    build:
      context: .
      dockerfile: MultiApiPost/Dockerfile

  multiapi:
    image: ${DOCKER_REGISTRY-}l2-multiapi-v6:v6
    build:
      context: .
      dockerfile: MultiApi/Dockerfile